### ISSUE TITLE
False Positive in url escaping

### ISSUE THREAD

**Issue by lakoza** [LibProtection/libprotection-dotnet#41]
There isn't sanitazation of third string:
**Format string:** {0}/{1}/{2}
**Data:** Assets
jsFile.js
?a

despite this case
**Format string:** {0}/{1}/{2}
**Data:** Assets
jsFile.js
a?

Although it's same by threat.

**Comment by kochetkov** [comment]
Thanks! This issue satisfies the conditions of the public testing program. Please contact me at vkochetkov@ptsecurity.com to get information on receiving prizes.

P.S: Strictly speaking -- an example of incorrect behavior is the second case, not the first one (due to the approach used in the library to determine the possibility of sanitization). But formally it's a bug and a false positive, yep.
